name: datapipes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytorch
  - rioxarray
  - torchdata
  - torchvision
  - xarray
  - fsspec
  - zarr
  - cartopy
  - dask
  - pyproj
  - pyresample
  - geopandas
  - h5netcdf
  - scipy
  - numba
  - pip:
      - einops
      - pathy
      - git+https://github.com/SheffieldSolar/PV_Live-API
      - pyaml_env
      - nowcasting_datamodel
      - gitpython
      - tqdm
      - bottleneck
