name: datapipes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - pytorch
  - rioxarray
  - torchvision
  - xarray
  - fsspec
  - zarr
  - cartopy
  - dask
  - pyproj
  - pyresample
  - geopandas
  - h5netcdf
  - scipy
  - pip:
      - einops
      - pathy
      - pyaml_env
      - nowcasting_datamodel
      - gitpython
      - tqdm
      - bottleneck
      - ocf_blosc2
      - pvlive-api
